version: '3.8'
services:
  php-apache-environment:
    images: nadzul/php
    container_name: php-apache
    depends_on:
      - db
    volumes:
      - php:./php/src:/var/www/html/
    ports:
      - 8000:80
    network:
      - backend
  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: php_user
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
      - ./php_user.sql:/docker-entrypoint-initdb.d/php_user.sql
    network:
      - backend

volumes:
  php: 
  db:

networks:
  name: backend-network
  ipam:
    driver: default
    config: 
      - subnet: 172.20.0.0/24

